Limit supported requests-cache versions
Recently installing this package and I run into this error:
```
...
pygbif/caching.py", line 2, in <module>
    from requests_cache.core import remove_expired_responses
ModuleNotFoundError: No module named 'requests_cache.core'
```
It seems that the `core` module was removed in requests-cache 0.8.0